language: python

python:
  - '3.3'
  - '3.4'

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - python -m unittest discover -s ./tests/ -p '*_test.py'
  - pylint --rcfile=.pylintrc --format=text --reports=n --confidence=high ircbot
  - pylint --rcfile=.pylintrc --format=text --reports=n --confidence=high plugins

sudo: false
