log_level: debug

plugins:
  redditeu: ircbot.plugin.redditeu.Plugin
  streams: ircbot.plugin.streams.Plugin
  qlranks: ircbot.plugin.qlranks.Plugin

bot:
  admins:
    - andreas@Raziel2p.users.quakenet.org
    - sid38082@ealing.irccloud.com
  bans:
    - Naypam@nay.verymad.net
  server: irc.quakenet.org:6667
  nick: rzbot
  username: pyircbot
  realname: pyircbot

channels:
  rzbot:
    plugins: []
  # redditeu:
  #   plugins: ['redditeu', 'streams']
  # qlreddit:
  #   plugins: ['qlranks', 'streams']
