# set this to null to log to STDOUT.
log_path: /var/log/ircbot.log
# available log levels: debug, info, warn, error
log_level: debug

bot:
  # the server to connect to
  server: irc.quakenet.org:6667
  # the nick to use
  nick: pyircbot
  # the username (ident)
  username: pyircbot
  # the real name - shows up in /whois
  realname: pyircbot
  # hosts of global admin users
  admins:
    - my.host.com
  # hosts of banned users
  bans:
    - banned.host.com
  # if you want to run a HTTP server for webhooks, uncomment these lines
  # http_host: localhost
  # http_port: 9123

# plugin map in the format of "name: classname"
# the class will be lazily imported and instantiated.
plugins:
  default: plugins.default.DefaultPlugin
  convert: plugins.convert.ConversionPlugin
  streams: plugins.streams.StreamsPlugin
  urls: plugins.urls.UrlPlugin

# plugins that are enabled in every channel
global_plugins:
  - default
  - urls

# channels the bot joins on connect. since the character starts a comment in
# YAML, wrap the channel name in quotes or leave out the #. each channel can
# have their own set of admins and plugins which only apply to that channel.
channels:
  mychannel:
    admins:
      - some.other.host.com
    plugins:
      - streams
  '##otherchannel':
    plugins:
      - convert

# uncomment these lines to enable the !mumble command
# mumble:
#   address: my.host.com
#   port: 64738
#   password: p4sSw0rD

# uncomment these lines to enable twitter text fetching
# twitter_api:
#   consumer_key: 'consumer_key'
#   consumer_secret: 'consumer_secret'
#   access_token: 'access_token'
#   access_token_secret: 'access_token_secret'
